# Generated by Django 5.0.2 on 2024-08-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('materia_nrc', models.ForeignKey(db_column='materia_nrc', on_delete=django.db.models.deletion.CASCADE, to='api.clase2')),
            ],
        ),
    ]
