# Generated by Django 5.0.2 on 2024-04-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='id_criterio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
